import { PrismaService } from '../../database/prisma.service';
export declare class ResearchService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    findAll(userId: string): Promise<{
        id: string;
        title: string;
        description: string;
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        studyType: import(".prisma/client").$Enums.StudyType;
        submittedAt: Date;
        createdAt: Date;
        creator: {
            email: string;
            name: string;
            id: string;
        };
        principalInvestigator: {
            email: string;
            name: string;
            id: string;
        };
    }[]>;
    findById(id: string, userId: string): Promise<{
        creator: {
            centerId: string | null;
            email: string;
            name: string;
            kolegiumId: string | null;
            passwordHash: string;
            phone: string | null;
            nik: string | null;
            id: string;
            isActive: boolean;
            isEmailVerified: boolean;
            mfaEnabled: boolean;
            mfaSecret: string | null;
            lastLoginAt: Date | null;
            isLocked: boolean;
            lockedUntil: Date | null;
            isSsoUser: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
        principalInvestigator: {
            centerId: string | null;
            email: string;
            name: string;
            kolegiumId: string | null;
            passwordHash: string;
            phone: string | null;
            nik: string | null;
            id: string;
            isActive: boolean;
            isEmailVerified: boolean;
            mfaEnabled: boolean;
            mfaSecret: string | null;
            lastLoginAt: Date | null;
            isLocked: boolean;
            lockedUntil: Date | null;
            isSsoUser: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    } & {
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
    create(data: any, userId: string): Promise<{
        creator: {
            centerId: string | null;
            email: string;
            name: string;
            kolegiumId: string | null;
            passwordHash: string;
            phone: string | null;
            nik: string | null;
            id: string;
            isActive: boolean;
            isEmailVerified: boolean;
            mfaEnabled: boolean;
            mfaSecret: string | null;
            lastLoginAt: Date | null;
            isLocked: boolean;
            lockedUntil: Date | null;
            isSsoUser: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
        principalInvestigator: {
            centerId: string | null;
            email: string;
            name: string;
            kolegiumId: string | null;
            passwordHash: string;
            phone: string | null;
            nik: string | null;
            id: string;
            isActive: boolean;
            isEmailVerified: boolean;
            mfaEnabled: boolean;
            mfaSecret: string | null;
            lastLoginAt: Date | null;
            isLocked: boolean;
            lockedUntil: Date | null;
            isSsoUser: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    } & {
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
    update(id: string, data: any, userId: string): Promise<{
        creator: {
            centerId: string | null;
            email: string;
            name: string;
            kolegiumId: string | null;
            passwordHash: string;
            phone: string | null;
            nik: string | null;
            id: string;
            isActive: boolean;
            isEmailVerified: boolean;
            mfaEnabled: boolean;
            mfaSecret: string | null;
            lastLoginAt: Date | null;
            isLocked: boolean;
            lockedUntil: Date | null;
            isSsoUser: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
        principalInvestigator: {
            centerId: string | null;
            email: string;
            name: string;
            kolegiumId: string | null;
            passwordHash: string;
            phone: string | null;
            nik: string | null;
            id: string;
            isActive: boolean;
            isEmailVerified: boolean;
            mfaEnabled: boolean;
            mfaSecret: string | null;
            lastLoginAt: Date | null;
            isLocked: boolean;
            lockedUntil: Date | null;
            isSsoUser: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    } & {
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
    delete(id: string, userId: string): Promise<{
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
}
