import { OnModuleInit } from '@nestjs/common';
import { PrismaService } from '@/database/prisma.service';
import { SyncOfflineDataDto } from './dto/sync-offline-data.dto';
import { ResolveConflictDto } from './dto/resolve-conflict.dto';
import { FileSyncService } from './file-sync.service';
import { RemotePrismaService } from '@/database/remote-prisma.service';
export declare class OfflineQueueService implements OnModuleInit {
    private prisma;
    private remotePrismaService;
    private fileSyncService;
    private readonly logger;
    private isSyncing;
    private isFileSyncing;
    private readonly phase1Entities;
    private readonly phase2Entities;
    private readonly phase3Entities;
    private readonly phase4Entities;
    private readonly phase5Entities;
    private readonly phase6Entities;
    private readonly phase7Entities;
    private readonly phase8Entities;
    private readonly phase9Entities;
    private readonly phase10Entities;
    private readonly phase11Entities;
    private readonly trackedEntities;
    constructor(prisma: PrismaService, remotePrismaService: RemotePrismaService, fileSyncService: FileSyncService);
    private get remotePrisma();
    onModuleInit(): Promise<void>;
    runFullSync(): Promise<{
        dataSync: any;
        status: string;
    }>;
    syncFiles(): Promise<any>;
    syncRemoteChanges(): Promise<any>;
    pullRemoteData(entityType: string): Promise<any>;
    private fetchRemoteChanges;
    private upsertLocal;
    queueOfflineData(syncDto: SyncOfflineDataDto, userId: string | null): Promise<any>;
    processQueueItem(queueId: string, userId: string | null): Promise<any>;
    syncAllPendingItems(): Promise<any>;
    resolveConflict(queueId: string, resolveDto: ResolveConflictDto, userId: string | null): Promise<any>;
    getPendingQueue(userId: string | null, limit?: number): Promise<any>;
    getQueueStatistics(userId: string | null): Promise<any>;
    private executeRemoteOperation;
    private handleGenericOperation;
    private handlePatientOperation;
    private handleDiagnosisOperation;
    private handleMedicationOperation;
    private handleClinicalPhotoOperation;
    private handleMstsScoreOperation;
    private fetchRemoteData;
}
