import { PrismaService } from '../../database/prisma.service';
import { CreateResearchRequestDto, UpdateResearchRequestDto, ApproveResearchRequestDto } from './dto/create-research-request.dto';
export declare class ResearchRequestsService {
    private prisma;
    constructor(prisma: PrismaService);
    create(userId: string, dto: CreateResearchRequestDto): Promise<{
        creator: {
            email: string;
            name: string;
            id: string;
        };
    } & {
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
    update(id: string, userId: string, dto: UpdateResearchRequestDto): Promise<{
        creator: {
            email: string;
            name: string;
            id: string;
        };
    } & {
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
    submit(id: string, userId: string): Promise<{
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
    findAll(userId: string, filters?: any): Promise<({
        creator: {
            email: string;
            name: string;
            id: string;
        };
    } & {
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    })[]>;
    findPending(): Promise<({
        creator: {
            email: string;
            name: string;
            id: string;
        };
        principalInvestigator: {
            email: string;
            name: string;
            id: string;
        };
    } & {
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    })[]>;
    findOne(id: string, userId?: string): Promise<{
        creator: {
            email: string;
            name: string;
            id: string;
        };
        activities: ({
            actor: {
                email: string;
                name: string;
            };
        } & {
            id: string;
            createdAt: Date;
            action: string;
            notes: string | null;
            researchRequestId: string;
            actorId: string;
            statusFrom: string | null;
            statusTo: string | null;
            metadata: import("@prisma/client/runtime/library").JsonValue | null;
        })[];
        principalInvestigator: {
            email: string;
            name: string;
            id: string;
        };
    } & {
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
    approveOrReject(id: string, adminId: string, dto: ApproveResearchRequestDto): Promise<{
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
    remove(id: string, userId: string): Promise<{
        message: string;
    }>;
    generateDataExport(id: string, adminId: string): Promise<{
        exportedCount: number;
        exportedFields: string[];
        csvContent: string;
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
    getDownloadUrl(id: string, userId: string): Promise<{
        downloadUrl: string;
        fileSize: number;
        expiresAt: Date;
        downloadCount: number;
    }>;
    trackDownload(id: string, userId: string): Promise<{
        status: import(".prisma/client").$Enums.ResearchRequestStatus;
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date | null;
        title: string;
        notes: string | null;
        requestNumber: string | null;
        principalInvestigatorId: string;
        studyType: import(".prisma/client").$Enums.StudyType;
        objectives: string;
        methodology: string;
        inclusionCriteria: string;
        exclusionCriteria: string;
        sampleSize: number;
        duration: number;
        requiresEthicsApproval: boolean;
        dataRequested: string;
        confidentialityRequirements: string | null;
        fundingSource: string | null;
        collaborators: string | null;
        ethicsStatus: import(".prisma/client").$Enums.EthicsStatus;
        ethicsApprovalNumber: string | null;
        ethicsApprovalDate: Date | null;
        priority: import(".prisma/client").$Enums.ResearchPriority;
        expectedOutcomes: string | null;
        riskAssessment: string | null;
        dataRetentionPeriod: number | null;
        submittedAt: Date | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        rejectedAt: Date | null;
        completedAt: Date | null;
        createdBy: string;
        researchAbstract: string | null;
        researcherPhone: string | null;
        researcherInstitution: string | null;
        requestedDataFields: import("@prisma/client/runtime/library").JsonValue | null;
        dataFilters: import("@prisma/client/runtime/library").JsonValue | null;
        estimatedPatientCount: number | null;
        dataSensitivityScore: number | null;
        isAutoApprovalEligible: boolean;
        needsEthicsReview: boolean;
        needsDataProtectionReview: boolean;
        irbCertificateUrl: string | null;
        protocolUrl: string | null;
        proposalUrl: string | null;
        cvUrl: string | null;
        agreementSigned: boolean;
        agreementDate: Date | null;
        dataExportGeneratedAt: Date | null;
        dataExportUrl: string | null;
        dataExportFileSize: number | null;
        dataDownloadedAt: Date | null;
        dataDownloadCount: number;
        requestingCenterId: string | null;
        approverRole: string | null;
        visibilityLevel: string | null;
    }>;
    requestExtension(id: string, userId: string, extensionMonths: number, justification: string): Promise<{
        message: string;
    }>;
    private logActivity;
}
