import { PrismaService } from '@/database/prisma.service';
import { CreatePatientDto, UpdatePatientDto } from './dto';
import { MedicalRecordService } from '../medical-record/medical-record.service';
export declare class PatientsEnhancedService {
    private prisma;
    private medicalRecordService;
    private readonly logger;
    constructor(prisma: PrismaService, medicalRecordService: MedicalRecordService);
    create(createDto: CreatePatientDto): Promise<{
        boneLocation: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            level: number;
            region: string;
            parentId: string | null;
            sortOrder: number;
            boneName: string | null;
            segment: string | null;
        };
        softTissueLocation: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            sortOrder: number;
            anatomicalRegion: string;
            specificLocation: string;
        };
        tumorSyndrome: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            geneticMarker: string | null;
            associatedTumors: string | null;
        };
        Center: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            province: string;
            regency: string | null;
            address: string | null;
            remoteDbUrl: string | null;
            remoteDbApiKey: string | null;
            mrPrefix: string | null;
            mrSequenceCounter: number;
            mrSequenceYear: number;
        };
        whoBoneTumor: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            diagnosis: string;
            category: string;
            subcategory: string;
            icdO3Code: string | null;
            pageReference: string | null;
            isMalignant: boolean;
            sortOrder: number;
        };
        whoSoftTissueTumor: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            diagnosis: string;
            category: string;
            subcategory: string;
            icdO3Code: string | null;
            isMalignant: boolean;
            sortOrder: number;
        };
    } & {
        pathologyType: string | null;
        mirrelScore: number | null;
        centerId: string;
        email: string | null;
        name: string;
        nik: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        province: string | null;
        regency: string | null;
        address: string | null;
        phoneNumber: string | null;
        hospitalRecordNumber: string | null;
        inamsosRecordNumber: string | null;
        anonymousId: string | null;
        dateOfBirth: Date;
        placeOfBirth: string | null;
        gender: import(".prisma/client").$Enums.Gender;
        bloodType: import(".prisma/client").$Enums.BloodType | null;
        religion: string | null;
        maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
        occupation: string | null;
        education: string | null;
        district: string | null;
        village: string | null;
        postalCode: string | null;
        emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
        isDeceased: boolean;
        dateOfDeath: Date | null;
        causeOfDeath: string | null;
        chiefComplaint: string | null;
        onsetDate: Date | null;
        symptomDuration: number | null;
        presentingSymptoms: string | null;
        tumorSizeAtPresentation: number | null;
        familyHistoryCancer: string | null;
        tumorSyndromeId: string | null;
        karnofskysScore: number | null;
        biopsyDate: Date | null;
        biopsyType: string | null;
        biopsyResult: string | null;
        imagingStudies: string | null;
        whoBoneTumorId: string | null;
        whoSoftTissueTumorId: string | null;
        boneLocationId: string | null;
        softTissueLocationId: string | null;
        laterality: string | null;
        histopathologyGrade: string | null;
        mitosisCount: number | null;
        necrosisPercentage: number | null;
        ennekingStage: string | null;
        ajccStage: string | null;
        tumorSizeT1: number | null;
        tumorSizeT2: number | null;
        tumorSizeT3: number | null;
        metastasisPresent: boolean | null;
        metastasisSites: string | null;
        cpcDate: Date | null;
        cpcRecommendation: string | null;
        intendedTreatment: string | null;
        createdById: string | null;
    }>;
    findAll(centerId?: string, pathologyType?: string, includeInactive?: boolean, page?: number, limit?: number, search?: string): Promise<{
        patients: {
            mstsScoreCount: any;
            followUpVisitCount: any;
            treatmentCount: any;
            cpcConferenceCount: any;
            _count: any;
            boneLocation: {
                id: string;
                code: string;
                level: number;
                region: string;
                boneName: string;
                segment: string;
            };
            softTissueLocation: {
                id: string;
                code: string;
                anatomicalRegion: string;
                specificLocation: string;
            };
            tumorSyndrome: {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                geneticMarker: string | null;
                associatedTumors: string | null;
            };
            Center: {
                name: string;
                id: string;
                code: string;
                province: string;
                regency: string;
            };
            whoBoneTumor: {
                id: string;
                diagnosis: string;
                category: string;
                subcategory: string;
                isMalignant: boolean;
            };
            whoSoftTissueTumor: {
                id: string;
                diagnosis: string;
                category: string;
                subcategory: string;
                isMalignant: boolean;
            };
            pathologyType: string | null;
            mirrelScore: number | null;
            centerId: string;
            email: string | null;
            name: string;
            nik: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            province: string | null;
            regency: string | null;
            address: string | null;
            phoneNumber: string | null;
            hospitalRecordNumber: string | null;
            inamsosRecordNumber: string | null;
            anonymousId: string | null;
            dateOfBirth: Date;
            placeOfBirth: string | null;
            gender: import(".prisma/client").$Enums.Gender;
            bloodType: import(".prisma/client").$Enums.BloodType | null;
            religion: string | null;
            maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
            occupation: string | null;
            education: string | null;
            district: string | null;
            village: string | null;
            postalCode: string | null;
            emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
            isDeceased: boolean;
            dateOfDeath: Date | null;
            causeOfDeath: string | null;
            chiefComplaint: string | null;
            onsetDate: Date | null;
            symptomDuration: number | null;
            presentingSymptoms: string | null;
            tumorSizeAtPresentation: number | null;
            familyHistoryCancer: string | null;
            tumorSyndromeId: string | null;
            karnofskysScore: number | null;
            biopsyDate: Date | null;
            biopsyType: string | null;
            biopsyResult: string | null;
            imagingStudies: string | null;
            whoBoneTumorId: string | null;
            whoSoftTissueTumorId: string | null;
            boneLocationId: string | null;
            softTissueLocationId: string | null;
            laterality: string | null;
            histopathologyGrade: string | null;
            mitosisCount: number | null;
            necrosisPercentage: number | null;
            ennekingStage: string | null;
            ajccStage: string | null;
            tumorSizeT1: number | null;
            tumorSizeT2: number | null;
            tumorSizeT3: number | null;
            metastasisPresent: boolean | null;
            metastasisSites: string | null;
            cpcDate: Date | null;
            cpcRecommendation: string | null;
            intendedTreatment: string | null;
            createdById: string | null;
        }[];
        total: number;
        page: number;
        totalPages: number;
    }>;
    findById(id: string, includeFullHistory?: boolean): Promise<{
        boneLocation: {
            parent: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                level: number;
                region: string;
                parentId: string | null;
                sortOrder: number;
                boneName: string | null;
                segment: string | null;
            };
            children: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                level: number;
                region: string;
                parentId: string | null;
                sortOrder: number;
                boneName: string | null;
                segment: string | null;
            }[];
        } & {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            level: number;
            region: string;
            parentId: string | null;
            sortOrder: number;
            boneName: string | null;
            segment: string | null;
        };
        softTissueLocation: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            sortOrder: number;
            anatomicalRegion: string;
            specificLocation: string;
        };
        tumorSyndrome: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            geneticMarker: string | null;
            associatedTumors: string | null;
        };
        Center: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            province: string;
            regency: string | null;
            address: string | null;
            remoteDbUrl: string | null;
            remoteDbApiKey: string | null;
            mrPrefix: string | null;
            mrSequenceCounter: number;
            mrSequenceYear: number;
        };
        _count: {
            mstsScores: number;
            followUpVisits: number;
            cpcConferences: number;
            treatments: number;
        };
        whoBoneTumor: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            diagnosis: string;
            category: string;
            subcategory: string;
            icdO3Code: string | null;
            pageReference: string | null;
            isMalignant: boolean;
            sortOrder: number;
        };
        whoSoftTissueTumor: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            diagnosis: string;
            category: string;
            subcategory: string;
            icdO3Code: string | null;
            isMalignant: boolean;
            sortOrder: number;
        };
        mstsScores: {
            function: number;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            patientId: string;
            notes: string | null;
            totalScore: number;
            assessmentDate: Date;
            assessedBy: string;
            followUpVisitId: string | null;
            pain: number;
            emotionalAcceptance: number;
            supports: number;
            walking: number;
            gait: number;
        }[];
        followUpVisits: {
            status: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            chiefComplaint: string | null;
            metastasisSites: string | null;
            patientId: string;
            notes: string | null;
            visitType: string;
            complications: string | null;
            karnofskyScore: number | null;
            physicalExamination: string | null;
            visitNumber: number;
            scheduledDate: Date;
            actualDate: Date | null;
            examinedBy: string | null;
            supportingExamination: string | null;
            clinicalStatus: string | null;
            localRecurrence: boolean | null;
            distantMetastasis: boolean | null;
            currentTreatment: string | null;
            mstsScoreId: string | null;
            imagingPerformed: string | null;
            imagingFindings: string | null;
            labResults: string | null;
            nextVisitDate: Date | null;
            reminderSent: boolean | null;
            reminderDate: Date | null;
            reminderMethod: string | null;
        }[];
        cpcConferences: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            patientId: string;
            recommendation: string;
            documentedBy: string;
            conferenceDate: Date;
            attendees: string;
            presentation: string | null;
            recommendationType: string;
            rationale: string | null;
            alternativeOptions: string | null;
            consensus: boolean;
            dissent: string | null;
        }[];
        treatments: {
            status: string;
            huvosGrade: string | null;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            patientId: string;
            notes: string | null;
            startDate: Date | null;
            endDate: Date | null;
            surgeryType: string | null;
            surgicalMargin: string | null;
            reconstructionMethod: string | null;
            radiotherapyDose: number | null;
            complications: string | null;
            performedBy: string | null;
            treatmentType: string;
            marginDistance: number | null;
            amputationLevel: string | null;
            chemotherapyProtocol: string | null;
            numberOfCycles: number | null;
            cyclesCompleted: number | null;
            numberOfFractions: number | null;
            fractionsCompleted: number | null;
            response: string | null;
            adverseEvents: string | null;
        }[];
    } & {
        pathologyType: string | null;
        mirrelScore: number | null;
        centerId: string;
        email: string | null;
        name: string;
        nik: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        province: string | null;
        regency: string | null;
        address: string | null;
        phoneNumber: string | null;
        hospitalRecordNumber: string | null;
        inamsosRecordNumber: string | null;
        anonymousId: string | null;
        dateOfBirth: Date;
        placeOfBirth: string | null;
        gender: import(".prisma/client").$Enums.Gender;
        bloodType: import(".prisma/client").$Enums.BloodType | null;
        religion: string | null;
        maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
        occupation: string | null;
        education: string | null;
        district: string | null;
        village: string | null;
        postalCode: string | null;
        emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
        isDeceased: boolean;
        dateOfDeath: Date | null;
        causeOfDeath: string | null;
        chiefComplaint: string | null;
        onsetDate: Date | null;
        symptomDuration: number | null;
        presentingSymptoms: string | null;
        tumorSizeAtPresentation: number | null;
        familyHistoryCancer: string | null;
        tumorSyndromeId: string | null;
        karnofskysScore: number | null;
        biopsyDate: Date | null;
        biopsyType: string | null;
        biopsyResult: string | null;
        imagingStudies: string | null;
        whoBoneTumorId: string | null;
        whoSoftTissueTumorId: string | null;
        boneLocationId: string | null;
        softTissueLocationId: string | null;
        laterality: string | null;
        histopathologyGrade: string | null;
        mitosisCount: number | null;
        necrosisPercentage: number | null;
        ennekingStage: string | null;
        ajccStage: string | null;
        tumorSizeT1: number | null;
        tumorSizeT2: number | null;
        tumorSizeT3: number | null;
        metastasisPresent: boolean | null;
        metastasisSites: string | null;
        cpcDate: Date | null;
        cpcRecommendation: string | null;
        intendedTreatment: string | null;
        createdById: string | null;
    }>;
    findByNIK(nik: string): Promise<{
        boneLocation: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            level: number;
            region: string;
            parentId: string | null;
            sortOrder: number;
            boneName: string | null;
            segment: string | null;
        };
        softTissueLocation: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            sortOrder: number;
            anatomicalRegion: string;
            specificLocation: string;
        };
        tumorSyndrome: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            geneticMarker: string | null;
            associatedTumors: string | null;
        };
        Center: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            province: string;
            regency: string | null;
            address: string | null;
            remoteDbUrl: string | null;
            remoteDbApiKey: string | null;
            mrPrefix: string | null;
            mrSequenceCounter: number;
            mrSequenceYear: number;
        };
        whoBoneTumor: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            diagnosis: string;
            category: string;
            subcategory: string;
            icdO3Code: string | null;
            pageReference: string | null;
            isMalignant: boolean;
            sortOrder: number;
        };
        whoSoftTissueTumor: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            diagnosis: string;
            category: string;
            subcategory: string;
            icdO3Code: string | null;
            isMalignant: boolean;
            sortOrder: number;
        };
    } & {
        pathologyType: string | null;
        mirrelScore: number | null;
        centerId: string;
        email: string | null;
        name: string;
        nik: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        province: string | null;
        regency: string | null;
        address: string | null;
        phoneNumber: string | null;
        hospitalRecordNumber: string | null;
        inamsosRecordNumber: string | null;
        anonymousId: string | null;
        dateOfBirth: Date;
        placeOfBirth: string | null;
        gender: import(".prisma/client").$Enums.Gender;
        bloodType: import(".prisma/client").$Enums.BloodType | null;
        religion: string | null;
        maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
        occupation: string | null;
        education: string | null;
        district: string | null;
        village: string | null;
        postalCode: string | null;
        emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
        isDeceased: boolean;
        dateOfDeath: Date | null;
        causeOfDeath: string | null;
        chiefComplaint: string | null;
        onsetDate: Date | null;
        symptomDuration: number | null;
        presentingSymptoms: string | null;
        tumorSizeAtPresentation: number | null;
        familyHistoryCancer: string | null;
        tumorSyndromeId: string | null;
        karnofskysScore: number | null;
        biopsyDate: Date | null;
        biopsyType: string | null;
        biopsyResult: string | null;
        imagingStudies: string | null;
        whoBoneTumorId: string | null;
        whoSoftTissueTumorId: string | null;
        boneLocationId: string | null;
        softTissueLocationId: string | null;
        laterality: string | null;
        histopathologyGrade: string | null;
        mitosisCount: number | null;
        necrosisPercentage: number | null;
        ennekingStage: string | null;
        ajccStage: string | null;
        tumorSizeT1: number | null;
        tumorSizeT2: number | null;
        tumorSizeT3: number | null;
        metastasisPresent: boolean | null;
        metastasisSites: string | null;
        cpcDate: Date | null;
        cpcRecommendation: string | null;
        intendedTreatment: string | null;
        createdById: string | null;
    }>;
    findByMRN(mrn: string): Promise<{
        boneLocation: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            level: number;
            region: string;
            parentId: string | null;
            sortOrder: number;
            boneName: string | null;
            segment: string | null;
        };
        softTissueLocation: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            sortOrder: number;
            anatomicalRegion: string;
            specificLocation: string;
        };
        tumorSyndrome: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            geneticMarker: string | null;
            associatedTumors: string | null;
        };
        Center: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            province: string;
            regency: string | null;
            address: string | null;
            remoteDbUrl: string | null;
            remoteDbApiKey: string | null;
            mrPrefix: string | null;
            mrSequenceCounter: number;
            mrSequenceYear: number;
        };
        whoBoneTumor: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            diagnosis: string;
            category: string;
            subcategory: string;
            icdO3Code: string | null;
            pageReference: string | null;
            isMalignant: boolean;
            sortOrder: number;
        };
        whoSoftTissueTumor: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            diagnosis: string;
            category: string;
            subcategory: string;
            icdO3Code: string | null;
            isMalignant: boolean;
            sortOrder: number;
        };
    } & {
        pathologyType: string | null;
        mirrelScore: number | null;
        centerId: string;
        email: string | null;
        name: string;
        nik: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        province: string | null;
        regency: string | null;
        address: string | null;
        phoneNumber: string | null;
        hospitalRecordNumber: string | null;
        inamsosRecordNumber: string | null;
        anonymousId: string | null;
        dateOfBirth: Date;
        placeOfBirth: string | null;
        gender: import(".prisma/client").$Enums.Gender;
        bloodType: import(".prisma/client").$Enums.BloodType | null;
        religion: string | null;
        maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
        occupation: string | null;
        education: string | null;
        district: string | null;
        village: string | null;
        postalCode: string | null;
        emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
        isDeceased: boolean;
        dateOfDeath: Date | null;
        causeOfDeath: string | null;
        chiefComplaint: string | null;
        onsetDate: Date | null;
        symptomDuration: number | null;
        presentingSymptoms: string | null;
        tumorSizeAtPresentation: number | null;
        familyHistoryCancer: string | null;
        tumorSyndromeId: string | null;
        karnofskysScore: number | null;
        biopsyDate: Date | null;
        biopsyType: string | null;
        biopsyResult: string | null;
        imagingStudies: string | null;
        whoBoneTumorId: string | null;
        whoSoftTissueTumorId: string | null;
        boneLocationId: string | null;
        softTissueLocationId: string | null;
        laterality: string | null;
        histopathologyGrade: string | null;
        mitosisCount: number | null;
        necrosisPercentage: number | null;
        ennekingStage: string | null;
        ajccStage: string | null;
        tumorSizeT1: number | null;
        tumorSizeT2: number | null;
        tumorSizeT3: number | null;
        metastasisPresent: boolean | null;
        metastasisSites: string | null;
        cpcDate: Date | null;
        cpcRecommendation: string | null;
        intendedTreatment: string | null;
        createdById: string | null;
    }>;
    update(id: string, updateDto: UpdatePatientDto): Promise<{
        boneLocation: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            level: number;
            region: string;
            parentId: string | null;
            sortOrder: number;
            boneName: string | null;
            segment: string | null;
        };
        softTissueLocation: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            sortOrder: number;
            anatomicalRegion: string;
            specificLocation: string;
        };
        tumorSyndrome: {
            description: string | null;
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            geneticMarker: string | null;
            associatedTumors: string | null;
        };
        Center: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            province: string;
            regency: string | null;
            address: string | null;
            remoteDbUrl: string | null;
            remoteDbApiKey: string | null;
            mrPrefix: string | null;
            mrSequenceCounter: number;
            mrSequenceYear: number;
        };
        whoBoneTumor: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            diagnosis: string;
            category: string;
            subcategory: string;
            icdO3Code: string | null;
            pageReference: string | null;
            isMalignant: boolean;
            sortOrder: number;
        };
        whoSoftTissueTumor: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            diagnosis: string;
            category: string;
            subcategory: string;
            icdO3Code: string | null;
            isMalignant: boolean;
            sortOrder: number;
        };
    } & {
        pathologyType: string | null;
        mirrelScore: number | null;
        centerId: string;
        email: string | null;
        name: string;
        nik: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        province: string | null;
        regency: string | null;
        address: string | null;
        phoneNumber: string | null;
        hospitalRecordNumber: string | null;
        inamsosRecordNumber: string | null;
        anonymousId: string | null;
        dateOfBirth: Date;
        placeOfBirth: string | null;
        gender: import(".prisma/client").$Enums.Gender;
        bloodType: import(".prisma/client").$Enums.BloodType | null;
        religion: string | null;
        maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
        occupation: string | null;
        education: string | null;
        district: string | null;
        village: string | null;
        postalCode: string | null;
        emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
        isDeceased: boolean;
        dateOfDeath: Date | null;
        causeOfDeath: string | null;
        chiefComplaint: string | null;
        onsetDate: Date | null;
        symptomDuration: number | null;
        presentingSymptoms: string | null;
        tumorSizeAtPresentation: number | null;
        familyHistoryCancer: string | null;
        tumorSyndromeId: string | null;
        karnofskysScore: number | null;
        biopsyDate: Date | null;
        biopsyType: string | null;
        biopsyResult: string | null;
        imagingStudies: string | null;
        whoBoneTumorId: string | null;
        whoSoftTissueTumorId: string | null;
        boneLocationId: string | null;
        softTissueLocationId: string | null;
        laterality: string | null;
        histopathologyGrade: string | null;
        mitosisCount: number | null;
        necrosisPercentage: number | null;
        ennekingStage: string | null;
        ajccStage: string | null;
        tumorSizeT1: number | null;
        tumorSizeT2: number | null;
        tumorSizeT3: number | null;
        metastasisPresent: boolean | null;
        metastasisSites: string | null;
        cpcDate: Date | null;
        cpcRecommendation: string | null;
        intendedTreatment: string | null;
        createdById: string | null;
    }>;
    remove(id: string): Promise<{
        pathologyType: string | null;
        mirrelScore: number | null;
        centerId: string;
        email: string | null;
        name: string;
        nik: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        province: string | null;
        regency: string | null;
        address: string | null;
        phoneNumber: string | null;
        hospitalRecordNumber: string | null;
        inamsosRecordNumber: string | null;
        anonymousId: string | null;
        dateOfBirth: Date;
        placeOfBirth: string | null;
        gender: import(".prisma/client").$Enums.Gender;
        bloodType: import(".prisma/client").$Enums.BloodType | null;
        religion: string | null;
        maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
        occupation: string | null;
        education: string | null;
        district: string | null;
        village: string | null;
        postalCode: string | null;
        emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
        isDeceased: boolean;
        dateOfDeath: Date | null;
        causeOfDeath: string | null;
        chiefComplaint: string | null;
        onsetDate: Date | null;
        symptomDuration: number | null;
        presentingSymptoms: string | null;
        tumorSizeAtPresentation: number | null;
        familyHistoryCancer: string | null;
        tumorSyndromeId: string | null;
        karnofskysScore: number | null;
        biopsyDate: Date | null;
        biopsyType: string | null;
        biopsyResult: string | null;
        imagingStudies: string | null;
        whoBoneTumorId: string | null;
        whoSoftTissueTumorId: string | null;
        boneLocationId: string | null;
        softTissueLocationId: string | null;
        laterality: string | null;
        histopathologyGrade: string | null;
        mitosisCount: number | null;
        necrosisPercentage: number | null;
        ennekingStage: string | null;
        ajccStage: string | null;
        tumorSizeT1: number | null;
        tumorSizeT2: number | null;
        tumorSizeT3: number | null;
        metastasisPresent: boolean | null;
        metastasisSites: string | null;
        cpcDate: Date | null;
        cpcRecommendation: string | null;
        intendedTreatment: string | null;
        createdById: string | null;
    }>;
    getPatientSummary(id: string): Promise<{
        patient: {
            id: string;
            mrn: string;
            hospitalMrn: string;
            nik: string;
            name: string;
            age: number;
            gender: import(".prisma/client").$Enums.Gender;
            center: string;
        };
        diagnosis: {
            pathologyType: string;
            whoBoneTumor: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                diagnosis: string;
                category: string;
                subcategory: string;
                icdO3Code: string | null;
                pageReference: string | null;
                isMalignant: boolean;
                sortOrder: number;
            };
            whoSoftTissueTumor: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                diagnosis: string;
                category: string;
                subcategory: string;
                icdO3Code: string | null;
                isMalignant: boolean;
                sortOrder: number;
            };
            boneLocation: {
                parent: {
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    code: string;
                    level: number;
                    region: string;
                    parentId: string | null;
                    sortOrder: number;
                    boneName: string | null;
                    segment: string | null;
                };
                children: {
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    code: string;
                    level: number;
                    region: string;
                    parentId: string | null;
                    sortOrder: number;
                    boneName: string | null;
                    segment: string | null;
                }[];
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                level: number;
                region: string;
                parentId: string | null;
                sortOrder: number;
                boneName: string | null;
                segment: string | null;
            };
            softTissueLocation: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                sortOrder: number;
                anatomicalRegion: string;
                specificLocation: string;
            };
            histopathologyGrade: string;
            ennekingStage: string;
            ajccStage: string;
            metastasisPresent: boolean;
        };
        clinical: {
            chiefComplaint: string;
            symptomDuration: number;
            tumorSize: number;
            karnofskysScore: number;
            biopsyResult: string;
        };
        mstsScores: {
            total: number;
            latest: {
                function: number;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                patientId: string;
                notes: string | null;
                totalScore: number;
                assessmentDate: Date;
                assessedBy: string;
                followUpVisitId: string | null;
                pain: number;
                emotionalAcceptance: number;
                supports: number;
                walking: number;
                gait: number;
            };
            average: number;
        };
        followUps: {
            total: number;
            completed: number;
            scheduled: number;
            missed: number;
            recurrenceDetected: boolean;
        };
        treatments: {
            total: number;
            byType: any;
            activeTreatments: number;
        };
        cpcConferences: {
            total: number;
            latest: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                patientId: string;
                recommendation: string;
                documentedBy: string;
                conferenceDate: Date;
                attendees: string;
                presentation: string | null;
                recommendationType: string;
                rationale: string | null;
                alternativeOptions: string | null;
                consensus: boolean;
                dissent: string | null;
            };
        };
    }>;
    getPatientStatistics(centerId?: string): Promise<{
        total: number;
        byPathologyType: {};
        byGender: {};
        deceased: number;
        withMetastasis: number;
        avgKarnofskysScore: number;
    }>;
    searchPatients(filters: any): Promise<{
        patients: ({
            boneLocation: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                level: number;
                region: string;
                parentId: string | null;
                sortOrder: number;
                boneName: string | null;
                segment: string | null;
            };
            softTissueLocation: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                sortOrder: number;
                anatomicalRegion: string;
                specificLocation: string;
            };
            Center: {
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                province: string;
                regency: string | null;
                address: string | null;
                remoteDbUrl: string | null;
                remoteDbApiKey: string | null;
                mrPrefix: string | null;
                mrSequenceCounter: number;
                mrSequenceYear: number;
            };
            whoBoneTumor: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                diagnosis: string;
                category: string;
                subcategory: string;
                icdO3Code: string | null;
                pageReference: string | null;
                isMalignant: boolean;
                sortOrder: number;
            };
            whoSoftTissueTumor: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                diagnosis: string;
                category: string;
                subcategory: string;
                icdO3Code: string | null;
                isMalignant: boolean;
                sortOrder: number;
            };
        } & {
            pathologyType: string | null;
            mirrelScore: number | null;
            centerId: string;
            email: string | null;
            name: string;
            nik: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            province: string | null;
            regency: string | null;
            address: string | null;
            phoneNumber: string | null;
            hospitalRecordNumber: string | null;
            inamsosRecordNumber: string | null;
            anonymousId: string | null;
            dateOfBirth: Date;
            placeOfBirth: string | null;
            gender: import(".prisma/client").$Enums.Gender;
            bloodType: import(".prisma/client").$Enums.BloodType | null;
            religion: string | null;
            maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
            occupation: string | null;
            education: string | null;
            district: string | null;
            village: string | null;
            postalCode: string | null;
            emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
            isDeceased: boolean;
            dateOfDeath: Date | null;
            causeOfDeath: string | null;
            chiefComplaint: string | null;
            onsetDate: Date | null;
            symptomDuration: number | null;
            presentingSymptoms: string | null;
            tumorSizeAtPresentation: number | null;
            familyHistoryCancer: string | null;
            tumorSyndromeId: string | null;
            karnofskysScore: number | null;
            biopsyDate: Date | null;
            biopsyType: string | null;
            biopsyResult: string | null;
            imagingStudies: string | null;
            whoBoneTumorId: string | null;
            whoSoftTissueTumorId: string | null;
            boneLocationId: string | null;
            softTissueLocationId: string | null;
            laterality: string | null;
            histopathologyGrade: string | null;
            mitosisCount: number | null;
            necrosisPercentage: number | null;
            ennekingStage: string | null;
            ajccStage: string | null;
            tumorSizeT1: number | null;
            tumorSizeT2: number | null;
            tumorSizeT3: number | null;
            metastasisPresent: boolean | null;
            metastasisSites: string | null;
            cpcDate: Date | null;
            cpcRecommendation: string | null;
            intendedTreatment: string | null;
            createdById: string | null;
        })[];
        total: number;
        page: any;
        totalPages: number;
    }>;
    private calculateAge;
    private calculateAverageMstsScore;
    private groupTreatmentsByType;
}
