import { PatientsEnhancedService } from './patients-enhanced.service';
import { CreatePatientDto, UpdatePatientDto, PatientDto } from './dto';
export declare class PatientsEnhancedController {
    private readonly patientsService;
    constructor(patientsService: PatientsEnhancedService);
    create(createDto: CreatePatientDto): Promise<PatientDto>;
    findAll(centerId?: string, pathologyType?: string, search?: string, includeInactive?: string, page?: string, limit?: string): Promise<{
        patients: {
            mstsScoreCount: any;
            followUpVisitCount: any;
            treatmentCount: any;
            cpcConferenceCount: any;
            _count: any;
            boneLocation: {
                id: string;
                code: string;
                level: number;
                region: string;
                boneName: string;
                segment: string;
            };
            softTissueLocation: {
                id: string;
                code: string;
                anatomicalRegion: string;
                specificLocation: string;
            };
            tumorSyndrome: {
                description: string | null;
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                geneticMarker: string | null;
                associatedTumors: string | null;
            };
            Center: {
                name: string;
                id: string;
                code: string;
                province: string;
                regency: string;
            };
            whoBoneTumor: {
                id: string;
                diagnosis: string;
                category: string;
                subcategory: string;
                isMalignant: boolean;
            };
            whoSoftTissueTumor: {
                id: string;
                diagnosis: string;
                category: string;
                subcategory: string;
                isMalignant: boolean;
            };
            pathologyType: string | null;
            mirrelScore: number | null;
            centerId: string;
            email: string | null;
            name: string;
            nik: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            province: string | null;
            regency: string | null;
            address: string | null;
            phoneNumber: string | null;
            hospitalRecordNumber: string | null;
            inamsosRecordNumber: string | null;
            anonymousId: string | null;
            dateOfBirth: Date;
            placeOfBirth: string | null;
            gender: import(".prisma/client").$Enums.Gender;
            bloodType: import(".prisma/client").$Enums.BloodType | null;
            religion: string | null;
            maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
            occupation: string | null;
            education: string | null;
            district: string | null;
            village: string | null;
            postalCode: string | null;
            emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
            isDeceased: boolean;
            dateOfDeath: Date | null;
            causeOfDeath: string | null;
            chiefComplaint: string | null;
            onsetDate: Date | null;
            symptomDuration: number | null;
            presentingSymptoms: string | null;
            tumorSizeAtPresentation: number | null;
            familyHistoryCancer: string | null;
            tumorSyndromeId: string | null;
            karnofskysScore: number | null;
            biopsyDate: Date | null;
            biopsyType: string | null;
            biopsyResult: string | null;
            imagingStudies: string | null;
            whoBoneTumorId: string | null;
            whoSoftTissueTumorId: string | null;
            boneLocationId: string | null;
            softTissueLocationId: string | null;
            laterality: string | null;
            histopathologyGrade: string | null;
            mitosisCount: number | null;
            necrosisPercentage: number | null;
            ennekingStage: string | null;
            ajccStage: string | null;
            tumorSizeT1: number | null;
            tumorSizeT2: number | null;
            tumorSizeT3: number | null;
            metastasisPresent: boolean | null;
            metastasisSites: string | null;
            cpcDate: Date | null;
            cpcRecommendation: string | null;
            intendedTreatment: string | null;
            createdById: string | null;
        }[];
        total: number;
        page: number;
        totalPages: number;
    }>;
    searchPatients(searchQuery: any): Promise<{
        patients: ({
            boneLocation: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                level: number;
                region: string;
                parentId: string | null;
                sortOrder: number;
                boneName: string | null;
                segment: string | null;
            };
            softTissueLocation: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                sortOrder: number;
                anatomicalRegion: string;
                specificLocation: string;
            };
            Center: {
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                province: string;
                regency: string | null;
                address: string | null;
                remoteDbUrl: string | null;
                remoteDbApiKey: string | null;
                mrPrefix: string | null;
                mrSequenceCounter: number;
                mrSequenceYear: number;
            };
            whoBoneTumor: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                diagnosis: string;
                category: string;
                subcategory: string;
                icdO3Code: string | null;
                pageReference: string | null;
                isMalignant: boolean;
                sortOrder: number;
            };
            whoSoftTissueTumor: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                diagnosis: string;
                category: string;
                subcategory: string;
                icdO3Code: string | null;
                isMalignant: boolean;
                sortOrder: number;
            };
        } & {
            pathologyType: string | null;
            mirrelScore: number | null;
            centerId: string;
            email: string | null;
            name: string;
            nik: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            province: string | null;
            regency: string | null;
            address: string | null;
            phoneNumber: string | null;
            hospitalRecordNumber: string | null;
            inamsosRecordNumber: string | null;
            anonymousId: string | null;
            dateOfBirth: Date;
            placeOfBirth: string | null;
            gender: import(".prisma/client").$Enums.Gender;
            bloodType: import(".prisma/client").$Enums.BloodType | null;
            religion: string | null;
            maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
            occupation: string | null;
            education: string | null;
            district: string | null;
            village: string | null;
            postalCode: string | null;
            emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
            isDeceased: boolean;
            dateOfDeath: Date | null;
            causeOfDeath: string | null;
            chiefComplaint: string | null;
            onsetDate: Date | null;
            symptomDuration: number | null;
            presentingSymptoms: string | null;
            tumorSizeAtPresentation: number | null;
            familyHistoryCancer: string | null;
            tumorSyndromeId: string | null;
            karnofskysScore: number | null;
            biopsyDate: Date | null;
            biopsyType: string | null;
            biopsyResult: string | null;
            imagingStudies: string | null;
            whoBoneTumorId: string | null;
            whoSoftTissueTumorId: string | null;
            boneLocationId: string | null;
            softTissueLocationId: string | null;
            laterality: string | null;
            histopathologyGrade: string | null;
            mitosisCount: number | null;
            necrosisPercentage: number | null;
            ennekingStage: string | null;
            ajccStage: string | null;
            tumorSizeT1: number | null;
            tumorSizeT2: number | null;
            tumorSizeT3: number | null;
            metastasisPresent: boolean | null;
            metastasisSites: string | null;
            cpcDate: Date | null;
            cpcRecommendation: string | null;
            intendedTreatment: string | null;
            createdById: string | null;
        })[];
        total: number;
        page: any;
        totalPages: number;
    }>;
    getStatistics(centerId?: string): Promise<{
        total: number;
        byPathologyType: {};
        byGender: {};
        deceased: number;
        withMetastasis: number;
        avgKarnofskysScore: number;
    }>;
    findByNIK(nik: string): Promise<PatientDto>;
    findByMRN(mrn: string): Promise<PatientDto>;
    getPatientSummary(id: string): Promise<{
        patient: {
            id: string;
            mrn: string;
            hospitalMrn: string;
            nik: string;
            name: string;
            age: number;
            gender: import(".prisma/client").$Enums.Gender;
            center: string;
        };
        diagnosis: {
            pathologyType: string;
            whoBoneTumor: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                diagnosis: string;
                category: string;
                subcategory: string;
                icdO3Code: string | null;
                pageReference: string | null;
                isMalignant: boolean;
                sortOrder: number;
            };
            whoSoftTissueTumor: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                diagnosis: string;
                category: string;
                subcategory: string;
                icdO3Code: string | null;
                isMalignant: boolean;
                sortOrder: number;
            };
            boneLocation: {
                parent: {
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    code: string;
                    level: number;
                    region: string;
                    parentId: string | null;
                    sortOrder: number;
                    boneName: string | null;
                    segment: string | null;
                };
                children: {
                    id: string;
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                    code: string;
                    level: number;
                    region: string;
                    parentId: string | null;
                    sortOrder: number;
                    boneName: string | null;
                    segment: string | null;
                }[];
            } & {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                level: number;
                region: string;
                parentId: string | null;
                sortOrder: number;
                boneName: string | null;
                segment: string | null;
            };
            softTissueLocation: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                sortOrder: number;
                anatomicalRegion: string;
                specificLocation: string;
            };
            histopathologyGrade: string;
            ennekingStage: string;
            ajccStage: string;
            metastasisPresent: boolean;
        };
        clinical: {
            chiefComplaint: string;
            symptomDuration: number;
            tumorSize: number;
            karnofskysScore: number;
            biopsyResult: string;
        };
        mstsScores: {
            total: number;
            latest: {
                function: number;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                patientId: string;
                notes: string | null;
                totalScore: number;
                assessmentDate: Date;
                assessedBy: string;
                followUpVisitId: string | null;
                pain: number;
                emotionalAcceptance: number;
                supports: number;
                walking: number;
                gait: number;
            };
            average: number;
        };
        followUps: {
            total: number;
            completed: number;
            scheduled: number;
            missed: number;
            recurrenceDetected: boolean;
        };
        treatments: {
            total: number;
            byType: any;
            activeTreatments: number;
        };
        cpcConferences: {
            total: number;
            latest: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                patientId: string;
                recommendation: string;
                documentedBy: string;
                conferenceDate: Date;
                attendees: string;
                presentation: string | null;
                recommendationType: string;
                rationale: string | null;
                alternativeOptions: string | null;
                consensus: boolean;
                dissent: string | null;
            };
        };
    }>;
    findById(id: string, includeFullHistory?: string): Promise<PatientDto>;
    update(id: string, updateDto: UpdatePatientDto): Promise<PatientDto>;
    remove(id: string): Promise<PatientDto>;
}
