import { VitalSignsService } from './vital-signs.service';
export declare class VitalSignsController {
    private readonly vitalSignsService;
    constructor(vitalSignsService: VitalSignsService);
    recordVitalSigns(createVitalSignsDto: {
        patientId: string;
        temperature?: number;
        systolicBP?: number;
        diastolicBP?: number;
        heartRate?: number;
        respiratoryRate?: number;
        oxygenSaturation?: number;
        weight?: number;
        height?: number;
        painScale?: number;
        bloodGlucose?: number;
        notes?: string;
        recordedBy: string;
    }): Promise<{
        id: string;
        patientId: string;
        notes: string | null;
        recordedAt: Date;
        temperature: number | null;
        bloodPressureSystolic: number | null;
        bloodPressureDiastolic: number | null;
        heartRate: number | null;
        respiratoryRate: number | null;
        oxygenSaturation: number | null;
        height: number | null;
        weight: number | null;
        bmi: number | null;
        painScale: number | null;
        bloodGlucose: number | null;
        recordedBy: string;
    }>;
    getVitalSignsByPatient(patientId: string, dateFrom?: string, dateTo?: string, limit?: string, offset?: string): Promise<any[]>;
    getLatestVitalSigns(patientId: string): Promise<{
        id: string;
        patientId: string;
        notes: string | null;
        recordedAt: Date;
        temperature: number | null;
        bloodPressureSystolic: number | null;
        bloodPressureDiastolic: number | null;
        heartRate: number | null;
        respiratoryRate: number | null;
        oxygenSaturation: number | null;
        height: number | null;
        weight: number | null;
        bmi: number | null;
        painScale: number | null;
        bloodGlucose: number | null;
        recordedBy: string;
    }>;
    getVitalSignsTrends(patientId: string, parameter: string, days?: string): Promise<any[]>;
    getAbnormalVitalSigns(patientId: string, hours?: string): Promise<any[]>;
    getAlerts(centerId?: string): Promise<any[]>;
    getVitalSignsStatistics(centerId?: string, days?: string): Promise<any>;
    getCriticalPatients(centerId?: string): Promise<any[]>;
    recordInitialAssessment(assessmentDto: {
        patientId: string;
        temperature: number;
        systolicBP: number;
        diastolicBP: number;
        heartRate: number;
        respiratoryRate: number;
        oxygenSaturation: number;
        weight?: number;
        height?: number;
        painScale?: number;
        assessmentNotes?: string;
        recordedBy: string;
    }): Promise<{
        id: string;
        patientId: string;
        notes: string | null;
        recordedAt: Date;
        temperature: number | null;
        bloodPressureSystolic: number | null;
        bloodPressureDiastolic: number | null;
        heartRate: number | null;
        respiratoryRate: number | null;
        oxygenSaturation: number | null;
        height: number | null;
        weight: number | null;
        bmi: number | null;
        painScale: number | null;
        bloodGlucose: number | null;
        recordedBy: string;
    }>;
    recordChemotherapyMonitoring(chemoDto: {
        patientId: string;
        temperature: number;
        systolicBP: number;
        diastolicBP: number;
        heartRate: number;
        respiratoryRate?: number;
        oxygenSaturation?: number;
        weight?: number;
        toxicity?: string;
        cycleNumber?: string;
        notes?: string;
        recordedBy: string;
    }): Promise<{
        id: string;
        patientId: string;
        notes: string | null;
        recordedAt: Date;
        temperature: number | null;
        bloodPressureSystolic: number | null;
        bloodPressureDiastolic: number | null;
        heartRate: number | null;
        respiratoryRate: number | null;
        oxygenSaturation: number | null;
        height: number | null;
        weight: number | null;
        bmi: number | null;
        painScale: number | null;
        bloodGlucose: number | null;
        recordedBy: string;
    }>;
    recordPreOperativeVitalSigns(preOpDto: {
        patientId: string;
        temperature: number;
        systolicBP: number;
        diastolicBP: number;
        heartRate: number;
        respiratoryRate: number;
        oxygenSaturation?: number;
        procedureType?: string;
        asaClass?: string;
        fastingStatus?: string;
        notes?: string;
        recordedBy: string;
    }): Promise<{
        id: string;
        patientId: string;
        notes: string | null;
        recordedAt: Date;
        temperature: number | null;
        bloodPressureSystolic: number | null;
        bloodPressureDiastolic: number | null;
        heartRate: number | null;
        respiratoryRate: number | null;
        oxygenSaturation: number | null;
        height: number | null;
        weight: number | null;
        bmi: number | null;
        painScale: number | null;
        bloodGlucose: number | null;
        recordedBy: string;
    }>;
    recordPostOperativeVitalSigns(postOpDto: {
        patientId: string;
        temperature: number;
        systolicBP: number;
        diastolicBP: number;
        heartRate: number;
        respiratoryRate: number;
        oxygenSaturation: number;
        painScale: number;
        consciousnessLevel?: string;
        bleeding?: string;
        procedureType?: string;
        postOpHour?: number;
        notes?: string;
        recordedBy: string;
    }): Promise<{
        id: string;
        patientId: string;
        notes: string | null;
        recordedAt: Date;
        temperature: number | null;
        bloodPressureSystolic: number | null;
        bloodPressureDiastolic: number | null;
        heartRate: number | null;
        respiratoryRate: number | null;
        oxygenSaturation: number | null;
        height: number | null;
        weight: number | null;
        bmi: number | null;
        painScale: number | null;
        bloodGlucose: number | null;
        recordedBy: string;
    }>;
}
