import { PrismaService } from '../../../database/prisma.service';
import { CreateFollowUpVisitDto, UpdateFollowUpVisitDto, GenerateFollowUpScheduleDto } from './dto/follow-up-visit.dto';
export declare class FollowUpsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    generateSchedule(dto: GenerateFollowUpScheduleDto): Promise<{
        patientId: string;
        totalVisits: number;
        message: string;
    }>;
    create(createDto: CreateFollowUpVisitDto): Promise<{
        status: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        chiefComplaint: string | null;
        metastasisSites: string | null;
        patientId: string;
        notes: string | null;
        visitType: string;
        complications: string | null;
        karnofskyScore: number | null;
        physicalExamination: string | null;
        visitNumber: number;
        scheduledDate: Date;
        actualDate: Date | null;
        examinedBy: string | null;
        supportingExamination: string | null;
        clinicalStatus: string | null;
        localRecurrence: boolean | null;
        distantMetastasis: boolean | null;
        currentTreatment: string | null;
        mstsScoreId: string | null;
        imagingPerformed: string | null;
        imagingFindings: string | null;
        labResults: string | null;
        nextVisitDate: Date | null;
        reminderSent: boolean | null;
        reminderDate: Date | null;
        reminderMethod: string | null;
    }>;
    findAll(patientId?: string, status?: string): Promise<({
        patient: {
            name: string;
            id: string;
            hospitalRecordNumber: string;
            inamsosRecordNumber: string;
        };
    } & {
        status: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        chiefComplaint: string | null;
        metastasisSites: string | null;
        patientId: string;
        notes: string | null;
        visitType: string;
        complications: string | null;
        karnofskyScore: number | null;
        physicalExamination: string | null;
        visitNumber: number;
        scheduledDate: Date;
        actualDate: Date | null;
        examinedBy: string | null;
        supportingExamination: string | null;
        clinicalStatus: string | null;
        localRecurrence: boolean | null;
        distantMetastasis: boolean | null;
        currentTreatment: string | null;
        mstsScoreId: string | null;
        imagingPerformed: string | null;
        imagingFindings: string | null;
        labResults: string | null;
        nextVisitDate: Date | null;
        reminderSent: boolean | null;
        reminderDate: Date | null;
        reminderMethod: string | null;
    })[]>;
    findOne(id: string): Promise<{
        patient: {
            name: string;
            id: string;
            hospitalRecordNumber: string;
            inamsosRecordNumber: string;
        };
    } & {
        status: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        chiefComplaint: string | null;
        metastasisSites: string | null;
        patientId: string;
        notes: string | null;
        visitType: string;
        complications: string | null;
        karnofskyScore: number | null;
        physicalExamination: string | null;
        visitNumber: number;
        scheduledDate: Date;
        actualDate: Date | null;
        examinedBy: string | null;
        supportingExamination: string | null;
        clinicalStatus: string | null;
        localRecurrence: boolean | null;
        distantMetastasis: boolean | null;
        currentTreatment: string | null;
        mstsScoreId: string | null;
        imagingPerformed: string | null;
        imagingFindings: string | null;
        labResults: string | null;
        nextVisitDate: Date | null;
        reminderSent: boolean | null;
        reminderDate: Date | null;
        reminderMethod: string | null;
    }>;
    findByPatient(patientId: string): Promise<{
        status: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        chiefComplaint: string | null;
        metastasisSites: string | null;
        patientId: string;
        notes: string | null;
        visitType: string;
        complications: string | null;
        karnofskyScore: number | null;
        physicalExamination: string | null;
        visitNumber: number;
        scheduledDate: Date;
        actualDate: Date | null;
        examinedBy: string | null;
        supportingExamination: string | null;
        clinicalStatus: string | null;
        localRecurrence: boolean | null;
        distantMetastasis: boolean | null;
        currentTreatment: string | null;
        mstsScoreId: string | null;
        imagingPerformed: string | null;
        imagingFindings: string | null;
        labResults: string | null;
        nextVisitDate: Date | null;
        reminderSent: boolean | null;
        reminderDate: Date | null;
        reminderMethod: string | null;
    }[]>;
    update(id: string, updateDto: UpdateFollowUpVisitDto): Promise<{
        status: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        chiefComplaint: string | null;
        metastasisSites: string | null;
        patientId: string;
        notes: string | null;
        visitType: string;
        complications: string | null;
        karnofskyScore: number | null;
        physicalExamination: string | null;
        visitNumber: number;
        scheduledDate: Date;
        actualDate: Date | null;
        examinedBy: string | null;
        supportingExamination: string | null;
        clinicalStatus: string | null;
        localRecurrence: boolean | null;
        distantMetastasis: boolean | null;
        currentTreatment: string | null;
        mstsScoreId: string | null;
        imagingPerformed: string | null;
        imagingFindings: string | null;
        labResults: string | null;
        nextVisitDate: Date | null;
        reminderSent: boolean | null;
        reminderDate: Date | null;
        reminderMethod: string | null;
    }>;
    remove(id: string): Promise<{
        status: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        chiefComplaint: string | null;
        metastasisSites: string | null;
        patientId: string;
        notes: string | null;
        visitType: string;
        complications: string | null;
        karnofskyScore: number | null;
        physicalExamination: string | null;
        visitNumber: number;
        scheduledDate: Date;
        actualDate: Date | null;
        examinedBy: string | null;
        supportingExamination: string | null;
        clinicalStatus: string | null;
        localRecurrence: boolean | null;
        distantMetastasis: boolean | null;
        currentTreatment: string | null;
        mstsScoreId: string | null;
        imagingPerformed: string | null;
        imagingFindings: string | null;
        labResults: string | null;
        nextVisitDate: Date | null;
        reminderSent: boolean | null;
        reminderDate: Date | null;
        reminderMethod: string | null;
    }>;
    getPatientFollowUpSummary(patientId: string): Promise<{
        patientId: string;
        totalVisits: number;
        completed: number;
        scheduled: number;
        missed: number;
        cancelled: number;
        upcomingVisit: {
            status: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            chiefComplaint: string | null;
            metastasisSites: string | null;
            patientId: string;
            notes: string | null;
            visitType: string;
            complications: string | null;
            karnofskyScore: number | null;
            physicalExamination: string | null;
            visitNumber: number;
            scheduledDate: Date;
            actualDate: Date | null;
            examinedBy: string | null;
            supportingExamination: string | null;
            clinicalStatus: string | null;
            localRecurrence: boolean | null;
            distantMetastasis: boolean | null;
            currentTreatment: string | null;
            mstsScoreId: string | null;
            imagingPerformed: string | null;
            imagingFindings: string | null;
            labResults: string | null;
            nextVisitDate: Date | null;
            reminderSent: boolean | null;
            reminderDate: Date | null;
            reminderMethod: string | null;
        };
        lastCompletedVisit: {
            status: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            chiefComplaint: string | null;
            metastasisSites: string | null;
            patientId: string;
            notes: string | null;
            visitType: string;
            complications: string | null;
            karnofskyScore: number | null;
            physicalExamination: string | null;
            visitNumber: number;
            scheduledDate: Date;
            actualDate: Date | null;
            examinedBy: string | null;
            supportingExamination: string | null;
            clinicalStatus: string | null;
            localRecurrence: boolean | null;
            distantMetastasis: boolean | null;
            currentTreatment: string | null;
            mstsScoreId: string | null;
            imagingPerformed: string | null;
            imagingFindings: string | null;
            labResults: string | null;
            nextVisitDate: Date | null;
            reminderSent: boolean | null;
            reminderDate: Date | null;
            reminderMethod: string | null;
        };
        recurrence: {
            local: boolean;
            distant: boolean;
        };
    }>;
}
