import { FollowUpsService } from './follow-ups.service';
import { FollowUpVisitDto, CreateFollowUpVisitDto, UpdateFollowUpVisitDto, GenerateFollowUpScheduleDto } from './dto/follow-up-visit.dto';
export declare class FollowUpsController {
    private readonly service;
    constructor(service: FollowUpsService);
    generateSchedule(dto: GenerateFollowUpScheduleDto): Promise<{
        patientId: string;
        totalVisits: number;
        message: string;
    }>;
    create(createDto: CreateFollowUpVisitDto): Promise<FollowUpVisitDto>;
    findAll(patientId?: string, status?: string): Promise<FollowUpVisitDto[]>;
    findByPatient(patientId: string): Promise<FollowUpVisitDto[]>;
    getPatientSummary(patientId: string): Promise<{
        patientId: string;
        totalVisits: number;
        completed: number;
        scheduled: number;
        missed: number;
        cancelled: number;
        upcomingVisit: {
            status: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            chiefComplaint: string | null;
            metastasisSites: string | null;
            patientId: string;
            notes: string | null;
            visitType: string;
            complications: string | null;
            karnofskyScore: number | null;
            physicalExamination: string | null;
            visitNumber: number;
            scheduledDate: Date;
            actualDate: Date | null;
            examinedBy: string | null;
            supportingExamination: string | null;
            clinicalStatus: string | null;
            localRecurrence: boolean | null;
            distantMetastasis: boolean | null;
            currentTreatment: string | null;
            mstsScoreId: string | null;
            imagingPerformed: string | null;
            imagingFindings: string | null;
            labResults: string | null;
            nextVisitDate: Date | null;
            reminderSent: boolean | null;
            reminderDate: Date | null;
            reminderMethod: string | null;
        };
        lastCompletedVisit: {
            status: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            chiefComplaint: string | null;
            metastasisSites: string | null;
            patientId: string;
            notes: string | null;
            visitType: string;
            complications: string | null;
            karnofskyScore: number | null;
            physicalExamination: string | null;
            visitNumber: number;
            scheduledDate: Date;
            actualDate: Date | null;
            examinedBy: string | null;
            supportingExamination: string | null;
            clinicalStatus: string | null;
            localRecurrence: boolean | null;
            distantMetastasis: boolean | null;
            currentTreatment: string | null;
            mstsScoreId: string | null;
            imagingPerformed: string | null;
            imagingFindings: string | null;
            labResults: string | null;
            nextVisitDate: Date | null;
            reminderSent: boolean | null;
            reminderDate: Date | null;
            reminderMethod: string | null;
        };
        recurrence: {
            local: boolean;
            distant: boolean;
        };
    }>;
    findOne(id: string): Promise<FollowUpVisitDto>;
    update(id: string, updateDto: UpdateFollowUpVisitDto): Promise<FollowUpVisitDto>;
    remove(id: string): Promise<FollowUpVisitDto>;
}
