import { PrismaService } from '../../../database/prisma.service';
export declare class LocationsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    private formatBoneLocationName;
    findAllBoneLocations(level?: number, region?: string, includeChildren?: boolean): Promise<{
        name: string;
        children: {
            name: string;
            children: {
                name: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                code: string;
                level: number;
                region: string;
                parentId: string | null;
                sortOrder: number;
                boneName: string | null;
                segment: string | null;
            }[];
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            level: number;
            region: string;
            parentId: string | null;
            sortOrder: number;
            boneName: string | null;
            segment: string | null;
        }[];
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        code: string;
        level: number;
        region: string;
        parentId: string | null;
        sortOrder: number;
        boneName: string | null;
        segment: string | null;
    }[]>;
    findBoneLocationById(id: string): Promise<{
        name: string;
        children: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            level: number;
            region: string;
            parentId: string | null;
            sortOrder: number;
            boneName: string | null;
            segment: string | null;
        }[];
        parent: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            level: number;
            region: string;
            parentId: string | null;
            sortOrder: number;
            boneName: string | null;
            segment: string | null;
        };
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        code: string;
        level: number;
        region: string;
        parentId: string | null;
        sortOrder: number;
        boneName: string | null;
        segment: string | null;
    }>;
    findBoneLocationsByParentId(parentId: string): Promise<{
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        code: string;
        level: number;
        region: string;
        parentId: string | null;
        sortOrder: number;
        boneName: string | null;
        segment: string | null;
    }[]>;
    private formatSoftTissueLocationName;
    findAllSoftTissueLocations(anatomicalRegion?: string): Promise<{
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        code: string;
        sortOrder: number;
        anatomicalRegion: string;
        specificLocation: string;
    }[]>;
    findSoftTissueLocationById(id: string): Promise<{
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        code: string;
        sortOrder: number;
        anatomicalRegion: string;
        specificLocation: string;
    }>;
    getBoneRegions(): Promise<{
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        code: string;
        level: number;
        region: string;
        parentId: string | null;
        sortOrder: number;
        boneName: string | null;
        segment: string | null;
    }[]>;
    getSoftTissueRegions(): Promise<string[]>;
}
