import { PrismaService } from '../../../database/prisma.service';
import { CreateTreatmentDto, UpdateTreatmentDto } from './dto/treatment.dto';
export declare class TreatmentsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(createDto: CreateTreatmentDto): Promise<{
        status: string;
        huvosGrade: string | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        notes: string | null;
        startDate: Date | null;
        endDate: Date | null;
        surgeryType: string | null;
        surgicalMargin: string | null;
        reconstructionMethod: string | null;
        radiotherapyDose: number | null;
        complications: string | null;
        performedBy: string | null;
        treatmentType: string;
        marginDistance: number | null;
        amputationLevel: string | null;
        chemotherapyProtocol: string | null;
        numberOfCycles: number | null;
        cyclesCompleted: number | null;
        numberOfFractions: number | null;
        fractionsCompleted: number | null;
        response: string | null;
        adverseEvents: string | null;
    }>;
    findAll(patientId?: string, treatmentType?: string, status?: string): Promise<({
        patient: {
            name: string;
            id: string;
            hospitalRecordNumber: string;
        };
    } & {
        status: string;
        huvosGrade: string | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        notes: string | null;
        startDate: Date | null;
        endDate: Date | null;
        surgeryType: string | null;
        surgicalMargin: string | null;
        reconstructionMethod: string | null;
        radiotherapyDose: number | null;
        complications: string | null;
        performedBy: string | null;
        treatmentType: string;
        marginDistance: number | null;
        amputationLevel: string | null;
        chemotherapyProtocol: string | null;
        numberOfCycles: number | null;
        cyclesCompleted: number | null;
        numberOfFractions: number | null;
        fractionsCompleted: number | null;
        response: string | null;
        adverseEvents: string | null;
    })[]>;
    findOne(id: string): Promise<{
        patient: {
            name: string;
            id: string;
            hospitalRecordNumber: string;
        };
    } & {
        status: string;
        huvosGrade: string | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        notes: string | null;
        startDate: Date | null;
        endDate: Date | null;
        surgeryType: string | null;
        surgicalMargin: string | null;
        reconstructionMethod: string | null;
        radiotherapyDose: number | null;
        complications: string | null;
        performedBy: string | null;
        treatmentType: string;
        marginDistance: number | null;
        amputationLevel: string | null;
        chemotherapyProtocol: string | null;
        numberOfCycles: number | null;
        cyclesCompleted: number | null;
        numberOfFractions: number | null;
        fractionsCompleted: number | null;
        response: string | null;
        adverseEvents: string | null;
    }>;
    findByPatient(patientId: string): Promise<{
        status: string;
        huvosGrade: string | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        notes: string | null;
        startDate: Date | null;
        endDate: Date | null;
        surgeryType: string | null;
        surgicalMargin: string | null;
        reconstructionMethod: string | null;
        radiotherapyDose: number | null;
        complications: string | null;
        performedBy: string | null;
        treatmentType: string;
        marginDistance: number | null;
        amputationLevel: string | null;
        chemotherapyProtocol: string | null;
        numberOfCycles: number | null;
        cyclesCompleted: number | null;
        numberOfFractions: number | null;
        fractionsCompleted: number | null;
        response: string | null;
        adverseEvents: string | null;
    }[]>;
    update(id: string, updateDto: UpdateTreatmentDto): Promise<{
        status: string;
        huvosGrade: string | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        notes: string | null;
        startDate: Date | null;
        endDate: Date | null;
        surgeryType: string | null;
        surgicalMargin: string | null;
        reconstructionMethod: string | null;
        radiotherapyDose: number | null;
        complications: string | null;
        performedBy: string | null;
        treatmentType: string;
        marginDistance: number | null;
        amputationLevel: string | null;
        chemotherapyProtocol: string | null;
        numberOfCycles: number | null;
        cyclesCompleted: number | null;
        numberOfFractions: number | null;
        fractionsCompleted: number | null;
        response: string | null;
        adverseEvents: string | null;
    }>;
    remove(id: string): Promise<{
        status: string;
        huvosGrade: string | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        notes: string | null;
        startDate: Date | null;
        endDate: Date | null;
        surgeryType: string | null;
        surgicalMargin: string | null;
        reconstructionMethod: string | null;
        radiotherapyDose: number | null;
        complications: string | null;
        performedBy: string | null;
        treatmentType: string;
        marginDistance: number | null;
        amputationLevel: string | null;
        chemotherapyProtocol: string | null;
        numberOfCycles: number | null;
        cyclesCompleted: number | null;
        numberOfFractions: number | null;
        fractionsCompleted: number | null;
        response: string | null;
        adverseEvents: string | null;
    }>;
    getPatientTreatmentSummary(patientId: string): Promise<{
        patientId: string;
        totalTreatments: number;
        byType: {
            surgery: number;
            chemotherapy: number;
            radiotherapy: number;
            targetedTherapy: number;
            immunotherapy: number;
        };
        byStatus: {
            planned: number;
            ongoing: number;
            completed: number;
            discontinued: number;
        };
        surgeryDetails: {
            id: string;
            surgeryType: string;
            surgicalMargin: string;
            reconstructionMethod: string;
            status: string;
        }[];
        activeChemotherapy: {
            status: string;
            huvosGrade: string | null;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            patientId: string;
            notes: string | null;
            startDate: Date | null;
            endDate: Date | null;
            surgeryType: string | null;
            surgicalMargin: string | null;
            reconstructionMethod: string | null;
            radiotherapyDose: number | null;
            complications: string | null;
            performedBy: string | null;
            treatmentType: string;
            marginDistance: number | null;
            amputationLevel: string | null;
            chemotherapyProtocol: string | null;
            numberOfCycles: number | null;
            cyclesCompleted: number | null;
            numberOfFractions: number | null;
            fractionsCompleted: number | null;
            response: string | null;
            adverseEvents: string | null;
        };
    }>;
}
