import { PrismaService } from '@/database/prisma.service';
import { Patient, Gender, BloodType, MaritalStatus } from '@prisma/client';
import { MedicalRecordService } from './services/medical-record.service';
export declare class PatientsService {
    private prisma;
    private medicalRecordService;
    private readonly logger;
    constructor(prisma: PrismaService, medicalRecordService: MedicalRecordService);
    findAll(centerId?: string, includeInactive?: boolean, page?: number, limit?: number, search?: string, user?: any): Promise<{
        patients: any[];
        total: number;
        page: number;
        totalPages: number;
    }>;
    findById(id: string, includeMedicalHistory?: boolean): Promise<any>;
    findByNIK(nik: string): Promise<Patient>;
    findByInamsosNumber(inamsosRecordNumber: string): Promise<Patient>;
    findByAnonymousId(anonymousId: string): Promise<Patient>;
    findByHospitalRecordNumber(hospitalRecordNumber: string): Promise<Patient>;
    create(patientData: {
        nik?: string;
        dateOfBirth: Date;
        placeOfBirth?: string;
        gender: Gender;
        bloodType?: BloodType;
        religion?: string;
        maritalStatus?: MaritalStatus;
        occupation?: string;
        education?: string;
        phoneNumber?: string;
        email?: string;
        address?: string;
        province?: string;
        regency?: string;
        district?: string;
        village?: string;
        postalCode?: string;
        emergencyContact?: any;
        centerId: string;
        hospitalRecordNumber?: string;
        diagnosisDate?: Date;
        createdBy?: string;
    }): Promise<Patient>;
    update(id: string, updateData: {
        nik?: string;
        phoneNumber?: string;
        email?: string;
        address?: string;
        province?: string;
        regency?: string;
        district?: string;
        village?: string;
        postalCode?: string;
        emergencyContact?: any;
        bloodType?: BloodType;
        religion?: string;
        maritalStatus?: MaritalStatus;
        occupation?: string;
        education?: string;
        hospitalRecordNumber?: string;
        isActive?: boolean;
        isDeceased?: boolean;
        dateOfDeath?: Date;
        causeOfDeath?: string;
    }): Promise<Patient>;
    getPatientStatistics(centerId?: string): Promise<any>;
    searchPatients(query: {
        search?: string;
        centerId?: string;
        gender?: Gender;
        bloodType?: BloodType;
        maritalStatus?: MaritalStatus;
        isDeceased?: boolean;
        dateOfBirthFrom?: Date;
        dateOfBirthTo?: Date;
        page?: number;
        limit?: number;
    }): Promise<{
        patients: any[];
        total: number;
        page: number;
        totalPages: number;
    }>;
    private calculateAge;
    private getAgeGroup;
    private getGenderStatistics;
    private getAgeStatistics;
    private getBloodTypeStatistics;
    private chatSessions;
    createChatSession(): Promise<{
        id: string;
        status: string;
        currentStep: number;
        totalSteps: number;
        messages: {
            id: string;
            type: string;
            content: string;
            timestamp: Date;
        }[];
        formData: {};
        createdAt: Date;
        updatedAt: Date;
    }>;
    getChatSession(sessionId: string): Promise<any>;
    sendChatMessage(sessionId: string, content: string, fieldName?: string, formData?: any): Promise<any>;
}
