import { PatientsService } from './patients.service';
import { Gender, BloodType, MaritalStatus } from '@prisma/client';
export declare class PatientsController {
    private readonly patientsService;
    constructor(patientsService: PatientsService);
    findAll(centerId?: string, search?: string, includeInactive?: string, page?: string, limit?: string, req?: any): Promise<{
        patients: any[];
        total: number;
        page: number;
        totalPages: number;
    }>;
    searchPatients(searchQuery: any): Promise<{
        patients: any[];
        total: number;
        page: number;
        totalPages: number;
    }>;
    getStatistics(centerId?: string): Promise<any>;
    findById(id: string, includeMedicalHistory?: string): Promise<any>;
    findByNIK(nik: string): Promise<{
        pathologyType: string | null;
        mirrelScore: number | null;
        centerId: string;
        email: string | null;
        name: string;
        nik: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        province: string | null;
        regency: string | null;
        address: string | null;
        phoneNumber: string | null;
        hospitalRecordNumber: string | null;
        inamsosRecordNumber: string | null;
        anonymousId: string | null;
        dateOfBirth: Date;
        placeOfBirth: string | null;
        gender: import(".prisma/client").$Enums.Gender;
        bloodType: import(".prisma/client").$Enums.BloodType | null;
        religion: string | null;
        maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
        occupation: string | null;
        education: string | null;
        district: string | null;
        village: string | null;
        postalCode: string | null;
        emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
        isDeceased: boolean;
        dateOfDeath: Date | null;
        causeOfDeath: string | null;
        chiefComplaint: string | null;
        onsetDate: Date | null;
        symptomDuration: number | null;
        presentingSymptoms: string | null;
        tumorSizeAtPresentation: number | null;
        familyHistoryCancer: string | null;
        tumorSyndromeId: string | null;
        karnofskysScore: number | null;
        biopsyDate: Date | null;
        biopsyType: string | null;
        biopsyResult: string | null;
        imagingStudies: string | null;
        whoBoneTumorId: string | null;
        whoSoftTissueTumorId: string | null;
        boneLocationId: string | null;
        softTissueLocationId: string | null;
        laterality: string | null;
        histopathologyGrade: string | null;
        mitosisCount: number | null;
        necrosisPercentage: number | null;
        ennekingStage: string | null;
        ajccStage: string | null;
        tumorSizeT1: number | null;
        tumorSizeT2: number | null;
        tumorSizeT3: number | null;
        metastasisPresent: boolean | null;
        metastasisSites: string | null;
        cpcDate: Date | null;
        cpcRecommendation: string | null;
        intendedTreatment: string | null;
        createdById: string | null;
    }>;
    findByMRN(mrn: string): Promise<{
        pathologyType: string | null;
        mirrelScore: number | null;
        centerId: string;
        email: string | null;
        name: string;
        nik: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        province: string | null;
        regency: string | null;
        address: string | null;
        phoneNumber: string | null;
        hospitalRecordNumber: string | null;
        inamsosRecordNumber: string | null;
        anonymousId: string | null;
        dateOfBirth: Date;
        placeOfBirth: string | null;
        gender: import(".prisma/client").$Enums.Gender;
        bloodType: import(".prisma/client").$Enums.BloodType | null;
        religion: string | null;
        maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
        occupation: string | null;
        education: string | null;
        district: string | null;
        village: string | null;
        postalCode: string | null;
        emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
        isDeceased: boolean;
        dateOfDeath: Date | null;
        causeOfDeath: string | null;
        chiefComplaint: string | null;
        onsetDate: Date | null;
        symptomDuration: number | null;
        presentingSymptoms: string | null;
        tumorSizeAtPresentation: number | null;
        familyHistoryCancer: string | null;
        tumorSyndromeId: string | null;
        karnofskysScore: number | null;
        biopsyDate: Date | null;
        biopsyType: string | null;
        biopsyResult: string | null;
        imagingStudies: string | null;
        whoBoneTumorId: string | null;
        whoSoftTissueTumorId: string | null;
        boneLocationId: string | null;
        softTissueLocationId: string | null;
        laterality: string | null;
        histopathologyGrade: string | null;
        mitosisCount: number | null;
        necrosisPercentage: number | null;
        ennekingStage: string | null;
        ajccStage: string | null;
        tumorSizeT1: number | null;
        tumorSizeT2: number | null;
        tumorSizeT3: number | null;
        metastasisPresent: boolean | null;
        metastasisSites: string | null;
        cpcDate: Date | null;
        cpcRecommendation: string | null;
        intendedTreatment: string | null;
        createdById: string | null;
    }>;
    create(createPatientDto: {
        name: string;
        nik: string;
        dateOfBirth: string;
        placeOfBirth?: string;
        gender: Gender;
        bloodType?: BloodType;
        religion?: string;
        maritalStatus?: MaritalStatus;
        occupation?: string;
        education?: string;
        phoneNumber?: string;
        email?: string;
        address?: string;
        province?: string;
        regency?: string;
        district?: string;
        village?: string;
        postalCode?: string;
        emergencyContact?: {
            name: string;
            relationship: string;
            phone: string;
        };
        centerId: string;
    }, req?: any): Promise<{
        pathologyType: string | null;
        mirrelScore: number | null;
        centerId: string;
        email: string | null;
        name: string;
        nik: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        province: string | null;
        regency: string | null;
        address: string | null;
        phoneNumber: string | null;
        hospitalRecordNumber: string | null;
        inamsosRecordNumber: string | null;
        anonymousId: string | null;
        dateOfBirth: Date;
        placeOfBirth: string | null;
        gender: import(".prisma/client").$Enums.Gender;
        bloodType: import(".prisma/client").$Enums.BloodType | null;
        religion: string | null;
        maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
        occupation: string | null;
        education: string | null;
        district: string | null;
        village: string | null;
        postalCode: string | null;
        emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
        isDeceased: boolean;
        dateOfDeath: Date | null;
        causeOfDeath: string | null;
        chiefComplaint: string | null;
        onsetDate: Date | null;
        symptomDuration: number | null;
        presentingSymptoms: string | null;
        tumorSizeAtPresentation: number | null;
        familyHistoryCancer: string | null;
        tumorSyndromeId: string | null;
        karnofskysScore: number | null;
        biopsyDate: Date | null;
        biopsyType: string | null;
        biopsyResult: string | null;
        imagingStudies: string | null;
        whoBoneTumorId: string | null;
        whoSoftTissueTumorId: string | null;
        boneLocationId: string | null;
        softTissueLocationId: string | null;
        laterality: string | null;
        histopathologyGrade: string | null;
        mitosisCount: number | null;
        necrosisPercentage: number | null;
        ennekingStage: string | null;
        ajccStage: string | null;
        tumorSizeT1: number | null;
        tumorSizeT2: number | null;
        tumorSizeT3: number | null;
        metastasisPresent: boolean | null;
        metastasisSites: string | null;
        cpcDate: Date | null;
        cpcRecommendation: string | null;
        intendedTreatment: string | null;
        createdById: string | null;
    }>;
    update(id: string, updatePatientDto: {
        name?: string;
        phoneNumber?: string;
        email?: string;
        address?: string;
        province?: string;
        regency?: string;
        district?: string;
        village?: string;
        postalCode?: string;
        emergencyContact?: {
            name: string;
            relationship: string;
            phone: string;
        };
        bloodType?: BloodType;
        religion?: string;
        maritalStatus?: MaritalStatus;
        occupation?: string;
        education?: string;
        isActive?: boolean;
        isDeceased?: boolean;
        dateOfDeath?: string;
        causeOfDeath?: string;
    }): Promise<{
        pathologyType: string | null;
        mirrelScore: number | null;
        centerId: string;
        email: string | null;
        name: string;
        nik: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        province: string | null;
        regency: string | null;
        address: string | null;
        phoneNumber: string | null;
        hospitalRecordNumber: string | null;
        inamsosRecordNumber: string | null;
        anonymousId: string | null;
        dateOfBirth: Date;
        placeOfBirth: string | null;
        gender: import(".prisma/client").$Enums.Gender;
        bloodType: import(".prisma/client").$Enums.BloodType | null;
        religion: string | null;
        maritalStatus: import(".prisma/client").$Enums.MaritalStatus | null;
        occupation: string | null;
        education: string | null;
        district: string | null;
        village: string | null;
        postalCode: string | null;
        emergencyContact: import("@prisma/client/runtime/library").JsonValue | null;
        isDeceased: boolean;
        dateOfDeath: Date | null;
        causeOfDeath: string | null;
        chiefComplaint: string | null;
        onsetDate: Date | null;
        symptomDuration: number | null;
        presentingSymptoms: string | null;
        tumorSizeAtPresentation: number | null;
        familyHistoryCancer: string | null;
        tumorSyndromeId: string | null;
        karnofskysScore: number | null;
        biopsyDate: Date | null;
        biopsyType: string | null;
        biopsyResult: string | null;
        imagingStudies: string | null;
        whoBoneTumorId: string | null;
        whoSoftTissueTumorId: string | null;
        boneLocationId: string | null;
        softTissueLocationId: string | null;
        laterality: string | null;
        histopathologyGrade: string | null;
        mitosisCount: number | null;
        necrosisPercentage: number | null;
        ennekingStage: string | null;
        ajccStage: string | null;
        tumorSizeT1: number | null;
        tumorSizeT2: number | null;
        tumorSizeT3: number | null;
        metastasisPresent: boolean | null;
        metastasisSites: string | null;
        cpcDate: Date | null;
        cpcRecommendation: string | null;
        intendedTreatment: string | null;
        createdById: string | null;
    }>;
    getPatientVitalSigns(id: string, limit?: string): Promise<{
        patientId: string;
        patientName: any;
        vitalSigns: any;
    }>;
    getPatientDiagnoses(id: string): Promise<{
        patientId: string;
        patientName: any;
        diagnoses: any;
    }>;
    getPatientMedications(id: string): Promise<{
        patientId: string;
        patientName: any;
        medications: any;
    }>;
    getPatientAllergies(id: string): Promise<{
        patientId: string;
        patientName: any;
        allergies: any;
    }>;
    getPatientVisits(id: string, limit?: string): Promise<{
        patientId: string;
        patientName: any;
        visits: any;
    }>;
    getPatientInsurance(id: string): Promise<{
        patientId: string;
        patientName: any;
        insuranceInfos: any;
    }>;
    createChatSession(): Promise<{
        id: string;
        status: string;
        currentStep: number;
        totalSteps: number;
        messages: {
            id: string;
            type: string;
            content: string;
            timestamp: Date;
        }[];
        formData: {};
        createdAt: Date;
        updatedAt: Date;
    }>;
    sendChatMessage(sessionId: string, body: {
        content: string;
        fieldName?: string;
        formData?: any;
    }): Promise<any>;
    getChatSession(sessionId: string): Promise<any>;
}
