// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetCachedUpdateInfo() {
  return window['go']['main']['App']['GetCachedUpdateInfo']();
}

export function GetCentralServerUrl() {
  return window['go']['main']['App']['GetCentralServerUrl']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportDataFromPath(arg1, arg2) {
  return window['go']['main']['App']['ImportDataFromPath'](arg1, arg2);
}

export function InstallUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallUpdate'](arg1, arg2, arg3);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PerformUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['PerformUpdate'](arg1, arg2, arg3);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}
