// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CreateBackup():Promise<main.BackupInfo>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:string,arg2:any):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetAuthStatus():Promise<Record<string, any>>;

export function GetCachedUpdateInfo():Promise<main.UpdateInfo>;

export function GetCentralServerUrl():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportDataFromPath(arg1:string,arg2:any):Promise<void>;

export function InstallUpdate(arg1:string,arg2:string,arg3:any):Promise<void>;

export function ListBackups():Promise<Array<main.BackupInfo>>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function PerformUpdate(arg1:string,arg2:boolean,arg3:any):Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;
